### ISSUE TITLE
User tours: pop-up triangle can look bad next to the rounded corners

### ISSUE THREAD

**Issue by HuongNV13** [andrewnicols/flexitour#7]
Sometimes, the triangle that attaches the user tour pop-up to the item being annotated can appear at the far right side. That looks ugly. We probably need to move the triangle a few pixels left in this case.
![image-2017-09-08-17-26-16-443](https://user-images.githubusercontent.com/11548406/34760156-3021d812-f611-11e7-9da3-72426610a334.png)
Expected result: the tour pop-up displays, and looks nice.
For more information: https://tracker.moodle.org/browse/MDL-60077

**Comment by andrewnicols** [comment]
Fixed in #8
